version: '3.7'
services:
  training-postgres:
    image: postgres:16.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: training
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin