version: '3.7'
services:
  training-postgres:
    image: postgres:16.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: training
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  training-mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: training
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - my-db-volume:/var/lib/mysql

volumes:
  my-db-volume:
